### ISSUE TITLE
NameError: uninitialized constant Builder

### ISSUE THREAD

**Issue by okliv** [kjvarga/sitemap_generator#225]
rails 4.1.8
ruby 2.2.1

```ruby
#config/sitemap.rb

SitemapGenerator::Sitemap.default_host = 'http://...'

SitemapGenerator::Sitemap.create do

...
#row 27
  add '/contacts', :changefreq => 'weekly'

end

````
if i run 

`$ RAILS_ENV=production rake sitemap:refresh`

i receive 

````

NameError: uninitialized constant Builder
/.../.rvm/gems/ruby-2.2.1@gemset/bundler/gems/sitemap_generator-028251269d39/lib/sitemap_generator/builder/sitemap_url.rb:72:in `to_xml'
/.../.rvm/gems/ruby-2.2.1@gemset/bundler/gems/sitemap_generator-028251269d39/lib/sitemap_generator/builder/sitemap_file.rb:102:in `add'
/.../.rvm/gems/ruby-2.2.1@gemset/bundler/gems/sitemap_generator-028251269d39/lib/sitemap_generator/link_set.rb:429:in `add_default_links'
/.../.rvm/gems/ruby-2.2.1@gemset/bundler/gems/sitemap_generator-028251269d39/lib/sitemap_generator/link_set.rb:145:in `add'
/.../.rvm/gems/ruby-2.2.1@gemset/bundler/gems/sitemap_generator-028251269d39/lib/sitemap_generator/interpreter.rb:31:in `add'
.../config/sitemap.rb:27:in `block in run'
/.../.rvm/gems/ruby-2.2.1@gemset/bundler/gems/sitemap_generator-028251269d39/lib/sitemap_generator/interpreter.rb:59:in `instance_eval'
/.../.rvm/gems/ruby-2.2.1@gemset/bundler/gems/sitemap_generator-028251269d39/lib/sitemap_generator/interpreter.rb:59:in `eval'
/.../.rvm/gems/ruby-2.2.1@gemset/bundler/gems/sitemap_generator-028251269d39/lib/sitemap_generator/link_set.rb:40:in `create'
/.../.rvm/gems/ruby-2.2.1@gemset/bundler/gems/sitemap_generator-028251269d39/lib/sitemap_generator.rb:42:in `method_missing'
/.../config/sitemap.rb:4:in `run'
/.../.rvm/gems/ruby-2.2.1@gemset/bundler/gems/sitemap_generator-028251269d39/lib/sitemap_generator/interpreter.rb:76:in `instance_eval'
/.../.rvm/gems/ruby-2.2.1@gemset/bundler/gems/sitemap_generator-028251269d39/lib/sitemap_generator/interpreter.rb:76:in `run'
/.../.rvm/gems/ruby-2.2.1@gemset/bundler/gems/sitemap_generator-028251269d39/lib/sitemap_generator/tasks.rb:51:in `block (2 levels) in <top (required)>'

````

google didn't help, gem version switches - too (tried 5.1.0, 5.0.5, 4.3.1), all hope is in you =)

(builder gem version is 3.2.2)

thank you

**Comment by okliv** [comment]
i found the reason but do not know how to fix it (yet)

it conflicts with https://github.com/andrad/alphasms-api (if i comment it out, sitemap generates as expected)

and now i need to figure out what gem causing this, actually

**Comment by okliv** [comment]
ahm... mystic

i have renamed here https://github.com/andrad/alphasms-api/tree/master/lib/alphasms

`builder.rb` to something else (`buildr.rb`) and problem just gone :/

closing issue
