### ISSUE TITLE
Aws::S3::Errors::AccessDenied: Access Denied

### ISSUE THREAD

**Issue by anthony-robin** [kjvarga/sitemap_generator#303]
After upgrading to v6.0.1, the upload of the sitemap on S3 throws me an `Aws::S3::Errors::AccessDenied: Access Denied`.

I saw the `path` option has been removed in this [commit](https://github.com/kjvarga/sitemap_generator/commit/1a6899635da0ac483b96764f70b43e7b3eab5da1#diff-9ab4fdb01b71e965a8095b3355dff0e5L25) and that seems to be the cause of the error because in v5.3.1 it’s working fine.

Extract of my code:

```ruby
# config/sitemap.rb

SitemapGenerator::Interpreter.send :include, SitemapHelper

if Rails.env.production?
  SitemapGenerator::Sitemap.adapter =
    SitemapGenerator::AwsSdkAdapter.new(
      ENV.fetch('AWS_BUCKET'),
      aws_access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID'),
      aws_secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY'),
      aws_region: ENV.fetch('AWS_REGION')
    )
end

SitemapGenerator::Sitemap.public_path = 'tmp/'
SitemapGenerator::Sitemap.sitemaps_host = 'https://mycloudfronturl.net/sitemap_catalog/'
SitemapGenerator::Sitemap.sitemaps_path = 'sitemap_catalog/'
```

And in s3, files are stored in `<bucket>/sitemap_catalog/`

Full stacktrace:
```
Aws::S3::Errors::AccessDenied: Access Denied
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-core-3.14.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-core-3.14.0/lib/seahorse/client/request.rb:70:in `send_request'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/client.rb:5463:in `put_object'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/file_uploader.rb:42:in `block in put_object'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/file_uploader.rb:49:in `open_file'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/file_uploader.rb:41:in `put_object'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/file_uploader.rb:34:in `upload'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/customizations/object.rb:252:in `upload_file'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/adapters/aws_sdk_adapter.rb:33:in `write'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/sitemap_location.rb:166:in `write'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/builder/sitemap_file.rb:139:in `write'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/builder/sitemap_index_file.rb:138:in `write_first_sitemap'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/builder/sitemap_index_file.rb:65:in `add'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/link_set.rb:166:in `add_to_index'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/link_set.rb:461:in `finalize_sitemap!'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/link_set.rb:239:in `group'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/interpreter.rb:45:in `group'
/Users/<user>/Code/<project>/config/sitemap.rb:27:in `block (2 levels) in run'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/interpreter.rb:61:in `instance_eval'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/interpreter.rb:61:in `eval'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/link_set.rb:40:in `create'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator.rb:41:in `method_missing'
/Users/<user>/Code/<project>/config/sitemap.rb:18:in `block in run'
/Users/<user>/Code/<project>/config/sitemap.rb:17:in `each'
/Users/<user>/Code/<project>/config/sitemap.rb:17:in `run'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/interpreter.rb:78:in `instance_eval'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/interpreter.rb:78:in `run'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/sitemap_generator-6.0.1/lib/sitemap_generator/tasks.rb:51:in `block (2 levels) in <top (required)>'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/Users/<user>/.rvm/gems/ruby-2.5.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
```

Did I miss something in the configuration ? How should I handle the removed `path` option in v6 ?
Thanks !

My project:
- Rails 5.1.4
- Ruby 2.5.0
- Sitemap generator 6.0.1
- Aws Sdk 3.0.1

**Comment by kjvarga** [comment]
@anthony-robin the `path` option is not needed, because users should configure their file location using the regular configuration methods, as you have done.  But I think the issue is in your `host`:

```
SitemapGenerator::Sitemap.sitemaps_host = 'https://mycloudfronturl.net'
SitemapGenerator::Sitemap.sitemaps_path = 'sitemap_catalog/'
```

That would create sitemap file links like `https://mycloudfronturl.net/sitemap_catalog/filename.xml.gz` and will attempt to upload your sitemap files to `<aws_url>/<aws_bucket>/sitemap_catalog/`

I don't see your `default_host` being set, but I assume you just didn't paste in your full config file.

**Comment by kjvarga** [comment]
Let me know if that resolves it.

**Comment by anthony-robin** [comment]
Thanks for your reply !

> I don't see your default_host being set, but I assume you just didn't paste in your full config file.

I haven’t set the `default_host` option as it is build dynamically in the `SitemapGenerator::Sitemap.create` action.

I tried to update my code according to your comment without more luck, with different combination with and without `/` at the end of `host` and `path`.

```ruby
SitemapGenerator::Sitemap.public_path = 'tmp/'
SitemapGenerator::Sitemap.sitemaps_host = 'https://xxxxxxxxxxxxx.cloudfront.net'
SitemapGenerator::Sitemap.sitemaps_path = 'sitemap_catalog/'
```

My main sitemap `sitemap.xml.gz` contain two links for sub sitemaps that are stored in `<bucket_name>/sitemap_catalog/files/` and that last folder already exists.

Can’t figure out if the problem come from the gem or from my AWS configuration but as it was working in `v5.3.1` I assume AWS credentials are ok.

Thanks !

**Comment by anthony-robin** [comment]
After a deeper investigation it seems that the problem come from the `acl` rules defined [here](https://github.com/kjvarga/sitemap_generator/blob/master/lib/sitemap_generator/adapters/aws_sdk_adapter.rb#L34). (without this line I am able to upload files to S3 but not to read them)

I don’t think it is related to the gem but might be from my aws config so I will close this issue for now.
Thanks for your help !

**Comment by kjvarga** [comment]
Ah yes, in order for sitemaps to be served from S3, which is the simplest setup, that location needs to be public readable.  Unless you're proxying your sitemaps or some other setup, you'll need that ACL rule.

**Comment by kovpack** [comment]
In my case it was a missing `PutObjectAcl` permission, too -  https://github.com/kjvarga/sitemap_generator/issues/357#issuecomment-869073523
