### ISSUE TITLE
Getting Google Cloud Storage Working with Fog Adapter

### ISSUE THREAD

**Issue by Petercopter** [kjvarga/sitemap_generator#324]
Greetings! This doesn't appear to be a problem with sitemap_generator, but I figured I'd start here. What does the config for the fog adapter look like? I feel like I'm close, but I'm getting an error when trying to upload the sitemap. It's generating locally, but things fall apart during the upload phase.

I am uploading to an existing bucket that was setup to use ActiveStorage. It seems like permissions are OK, and I've connected using Fog while trying to debug. I've got the fog-google gem installed. https://github.com/fog/fog-google

Here's the configuration I've cobbled together:
```
SitemapGenerator::Sitemap.adapter = SitemapGenerator::FogAdapter.new(
  fog_credentials: {
    provider: 'google',
    google_project: 'my_project_id',
    google_json_key_location: Rails.root.join('google_storage_key.json')
  },
  fog_bucket: 'development-fog-bucket'
)
```
In the logs I'm seeing this, but notice the `/b//o` in the path, it seems like maybe I'm missing a variable that I should be passing....
```
Sending upload start command to https://www.googleapis.com/upload/storage/v1/b//o?predefinedAcl=publicRead
Upload status final
Error - #<Google::Apis::ClientError: Invalid request>
```
Here's the full trace
```
$ rake sitemap:create --trace
** Invoke sitemap:create (first_time)
** Invoke sitemap:require_environment (first_time)
** Execute sitemap:require_environment
** Invoke environment (first_time)
** Execute environment
** Execute sitemap:create
In '/Users/petercopter/projects/wowgrind/tmp/':
rake aborted!
Google::Apis::ClientError: Invalid request
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:218:in `check_status'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-api-client-0.23.9/lib/google/apis/core/api_command.rb:116:in `check_status'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:183:in `process_response'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-api-client-0.23.9/lib/google/apis/core/upload.rb:170:in `process_response'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-api-client-0.23.9/lib/google/apis/core/upload.rb:246:in `execute_once'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:101:in `block in execute'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-api-client-0.23.9/lib/google/apis/core/http_command.rb:93:in `execute'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-api-client-0.23.9/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/google-api-client-0.23.9/generated/google/apis/storage_v1/service.rb:1897:in `insert_object'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fog-google-1.8.2/lib/fog/storage/google_json/requests/put_object.rb:57:in `put_object'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fog-google-1.8.2/lib/fog/storage/google_json/models/file.rb:108:in `save'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:50:in `create'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sitemap_generator-6.0.2/lib/sitemap_generator/adapters/fog_adapter.rb:25:in `write'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sitemap_generator-6.0.2/lib/sitemap_generator/sitemap_location.rb:166:in `write'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sitemap_generator-6.0.2/lib/sitemap_generator/builder/sitemap_file.rb:139:in `write'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sitemap_generator-6.0.2/lib/sitemap_generator/builder/sitemap_index_file.rb:139:in `write_first_sitemap'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sitemap_generator-6.0.2/lib/sitemap_generator/builder/sitemap_index_file.rb:105:in `finalize!'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sitemap_generator-6.0.2/lib/sitemap_generator/link_set.rb:470:in `finalize_sitemap_index!'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sitemap_generator-6.0.2/lib/sitemap_generator/link_set.rb:341:in `finalize!'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sitemap_generator-6.0.2/lib/sitemap_generator/link_set.rb:41:in `create'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sitemap_generator-6.0.2/lib/sitemap_generator.rb:41:in `method_missing'
/Users/petercopter/projects/wowgrind/config/sitemap.rb:16:in `run'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sitemap_generator-6.0.2/lib/sitemap_generator/interpreter.rb:78:in `instance_eval'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sitemap_generator-6.0.2/lib/sitemap_generator/interpreter.rb:78:in `run'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/sitemap_generator-6.0.2/lib/sitemap_generator/tasks.rb:51:in `block (2 levels) in <main>'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/Users/petercopter/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/petercopter/.rbenv/versions/2.6.1/bin/rake:23:in `load'
/Users/petercopter/.rbenv/versions/2.6.1/bin/rake:23:in `<main>'
Tasks: TOP => sitemap:create
```

**Comment by pbasl** [comment]
One possible issue in your configuration is you should use '`fog_directory`' instead of '`fog_bucket`'

**Comment by kjvarga** [comment]
Sorry I'm not familiar with Fog and can't provide support.
