### ISSUE TITLE
Aws::S3::Errors::AccessDenied: Access Denied

### ISSUE THREAD

**Issue by luigi7up** [kjvarga/sitemap_generator#357]
Hi guys, I'm using this setup in order to upload my sitemaps to a S3 bucket:

```
SitemapGenerator::Sitemap.adapter = SitemapGenerator::AwsSdkAdapter.new(
  ENV["S3_BUCKET"],
  aws_access_key_id: ENV["AWS_ACCESS_KEY_ID"],
  aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
  aws_region: "eu-west-3" # e.g. 'us-east-1'
)

SitemapGenerator::Sitemap.public_path = 'tmp/'
SitemapGenerator::Sitemap.sitemaps_host = "http://s3.#{ENV["AWS_REGION"]}.amazonaws.com/#{ENV["S3_BUCKET"]}"
SitemapGenerator::Sitemap.sitemaps_path = 'sitemaps/'
```

When I run `rake sitemap:create` I get the following error `Aws::S3::Errors::AccessDenied: Access Denied` with this trace:

```
gems/ruby-2.5.1@trasteros/gems/aws-sdk-core-3.99.2/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-s3-1.68.1/lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-s3-1.68.1/lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-s3-1.68.1/lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-core-3.99.2/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-core-3.99.2/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-core-3.99.2/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-core-3.99.2/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-core-3.99.2/lib/seahorse/client/plugins/response_target.rb:23:in `call'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-core-3.99.2/lib/seahorse/client/request.rb:70:in `send_request'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-s3-1.68.1/lib/aws-sdk-s3/client.rb:9570:in `put_object'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-s3-1.68.1/lib/aws-sdk-s3/file_uploader.rb:51:in `block in put_object'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-s3-1.68.1/lib/aws-sdk-s3/file_uploader.rb:43:in `block in open_file'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-s3-1.68.1/lib/aws-sdk-s3/file_uploader.rb:43:in `open'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-s3-1.68.1/lib/aws-sdk-s3/file_uploader.rb:43:in `open_file'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-s3-1.68.1/lib/aws-sdk-s3/file_uploader.rb:50:in `put_object'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-s3-1.68.1/lib/aws-sdk-s3/file_uploader.rb:35:in `upload'
gems/ruby-2.5.1@trasteros/gems/aws-sdk-s3-1.68.1/lib/aws-sdk-s3/customizations/object.rb:328:in `upload_file'
gems/ruby-2.5.1@trasteros/gems/sitemap_generator-6.1.2/lib/sitemap_generator/adapters/aws_sdk_adapter.rb:34:in `write'
gems/ruby-2.5.1@trasteros/gems/sitemap_generator-6.1.2/lib/sitemap_generator/sitemap_location.rb:166:in `write'
gems/ruby-2.5.1@trasteros/gems/sitemap_generator-6.1.2/lib/sitemap_generator/builder/sitemap_file.rb:139:in `write'
gems/ruby-2.5.1@trasteros/gems/sitemap_generator-6.1.2/lib/sitemap_generator/builder/sitemap_index_file.rb:139:in `write_first_sitemap'
gems/ruby-2.5.1@trasteros/gems/sitemap_generator-6.1.2/lib/sitemap_generator/builder/sitemap_index_file.rb:105:in `finalize!'
gems/ruby-2.5.1@trasteros/gems/sitemap_generator-6.1.2/lib/sitemap_generator/link_set.rb:474:in `finalize_sitemap_index!'
gems/ruby-2.5.1@trasteros/gems/sitemap_generator-6.1.2/lib/sitemap_generator/link_set.rb:345:in `finalize!'
gems/ruby-2.5.1@trasteros/gems/sitemap_generator-6.1.2/lib/sitemap_generator/link_set.rb:41:in `create'
gems/ruby-2.5.1@trasteros/gems/sitemap_generator-6.1.2/lib/sitemap_generator.rb:42:in `method_missing'
/Users/luka/projects/pinabox/config/sitemap.rb:26:in `run'
gems/ruby-2.5.1@trasteros/gems/sitemap_generator-6.1.2/lib/sitemap_generator/interpreter.rb:78:in `instance_eval'
gems/ruby-2.5.1@trasteros/gems/sitemap_generator-6.1.2/lib/sitemap_generator/interpreter.rb:78:in `run'
gems/ruby-2.5.1@trasteros/gems/sitemap_generator-6.1.2/lib/sitemap_generator/tasks.rb:51:in `block (2 levels) in <top (required)>'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
gems/ruby-2.5.1@trasteros/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
gems/ruby-2.5.1@trasteros/bin/rake:23:in `load'
gems/ruby-2.5.1@trasteros/bin/rake:23:in `<main>'
gems/ruby-2.5.1@trasteros/bin/ruby_executable_hooks:24:in `eval'
gems/ruby-2.5.1@trasteros/bin/ruby_executable_hooks:24:in `<main>'
```

It definitely looks like a AWS permissions problem, but I use the same S3 user I already use for Active Storage uploads - which works totally fine so I'd say that IAM policy permissions should be fine.

Here is my AWS user's policy setup:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:GetAccessPoint",
                "s3:PutAccountPublicAccessBlock",
                "s3:GetAccountPublicAccessBlock",
                "s3:ListAllMyBuckets",
                "s3:ListAccessPoints",
                "s3:ListJobs",
                "s3:CreateJob",
                "s3:HeadBucket",
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:PutObjectAcl"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "*"
        }
    ]
}
```

I'm not a cloud expert, but this is a quite permissive policy :/ so I guess this should definitely work :(

Best regards

**Comment by Curting** [comment]
Hi luigi7up,

After hours of encountering the same problem as you, these bucket settings finally solved it for me:
![Screenshot 13-08-2020 at 07 23 49](https://user-images.githubusercontent.com/20524783/90097337-fadcc900-dd35-11ea-825f-0aa25f904d2b.png)

I hope it can help you as well :-)

**Comment by kjvarga** [comment]
Sorry I can't help with individual issues with your externally hosted sitemaps.  It's invariably an issue with the permissions that you have set up.

**Comment by kovpack** [comment]
Just in case someone else gets stuck on this one, even after having made things public.

In my case the problem was in this method:

```
    def write(location, raw_data)
      SitemapGenerator::FileAdapter.new.write(location, raw_data)
      s3_object = s3_resource.bucket(@bucket).object(location.path_in_public)
      s3_object.upload_file(location.path,
        acl: 'public-read',
        cache_control: 'private, max-age=0, no-cache',
        content_type: location[:compress] ? 'application/x-gzip' : 'application/xml'
      )
    end
```

Without `acl: 'public-read'` option it was working just fine. 

And this means that in addition to the creation of an object, it also tries to manage permissions, which is a separate setting in the policy - `PutObjectAcl`.

**Comment by g1eyd50n** [comment]
Thanks, @kovpack this worked perfectly
